### ISSUE TITLE
Add Original PDF

### ISSUE THREAD

**Issue by loganfranken** [ucsb-wsg/web-accessibility#1]
I think the first step is to simply add the PDF in-question to this repo:
http://webguide.ucsb.edu/media/web-accessibility-guidelines.pdf

**Comment by tenken** [comment]
Kinda sucks there is only a PDF. I've tried like the linux `pdftohtml` command, a similar php wrapper to the linux command and PDFBox from Apache project to convert it all to html but because its in say PDF and not Word you get meaningless useless garbage out of hte conversion. I even tried opening the PDF in like LibreOffice and saving as HTML -- equally trashy output. And i looked for `.doc` files in the WSG group on it.ucsb.edu and found no alternative.

I suspect a massive copy-paste fest is required.

**Comment by loganfranken** [comment]
Aww, that sucks. :-1:

Yeah, I figured the process could end up being fairly manual: either way, though, I figured adding the actual PDF itself would be the place to start.

**Comment by loganfranken** [comment]
Hey there! Any reason we don't want to move forward with this PR? (Just figured we could start by adding the source PDF before converting it to text; totally open to other suggestions, though!)
